name: Next.js High-Quality CI

on:
  push:
    branches: [main, master, dev]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Code Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint . --ext .ts,.js,.tsx,.jsx
      - name: Run Prettier Check
        run: npx prettier --check .

  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test

  security:
    name: Security & Dependency Audit
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Audit dependencies
        run: npm audit --audit-level=moderate

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build Next.js
        run: npm run build

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Deploy
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

  notify:
    name: Notify Completion
    runs-on: ubuntu-latest
    needs: [lint, test, security, build, deploy]
    steps:
      - name: Notify
        run: echo "CI/CD completed. Review results and address any issues."
